---
# Defaults pour le role ad-join

# Configuration du domaine Active Directory
ad_domain: "proto.lan"
ad_realm: "PROTO.LAN"  # En MAJUSCULES
ad_dc_ip: "10.0.0.5"

# Compte de service pour joindre le domaine
ad_join_user: "svc_ansible"
# Le mot de passe est dans group_vars/all/vault.yml (chiffré)

# Configuration SSSD
ad_use_fqdn: false  # Permet de se connecter avec juste "ubuntu_admin" au lieu de "ubuntu_admin@proto.lan"
ad_fallback_homedir: "/home/%u"  # Crée /home/ubuntu_admin

# Packages nécessaires
ad_packages:
  - realmd
  - sssd
  - sssd-tools
  - libnss-sss
  - libpam-sss
  - adcli
  - samba-common-bin
  - packagekit
  - chrony  # Pour la synchro temps (important pour Kerberos!)

