---
galaxy_info:
  author: TomGn1
  description: Role pour joindre des VMs Ubuntu au domaine Active Directory
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - jammy  # 22.04

dependencies: []
