---
all:
  children:
    domain_vms:
      hosts:
        # Les VMs seront ajout√©es dynamiquement ou manuellement ici
        # Exemple :
         UBUNTU-DEV1:
           ansible_host: 10.0.0.121
         UBUNTU-DEV2:
           ansible_host: 10.0.0.120
         UBUNTU-DEV3:
           ansible_host: 10.0.0.122
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_python_interpreter: /usr/bin/python3
        ansible_become: yes
        ansible_become_method: sudo
